### ISSUE TITLE
StreamClosedException when requesting for Yaml representations

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#1008]
tested scenario:
 - application using the internal connector
 - using the Jackson extension
 - client asks for yaml representation of a Java bean

There is a stack trace on server side:

```
SEVERE: An exception occured writing the response entity
sun.net.httpserver.StreamClosedException
	at sun.net.httpserver.ChunkedOutputStream.flush(ChunkedOutputStream.java:156)
	at sun.net.httpserver.PlaceholderOutputStream.flush(ExchangeImpl.java:449)
	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:511)
	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:454)
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:187)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
	at org.restlet.engine.connector.HttpServerHelper$1.handle(HttpServerHelper.java:64)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:677)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:649)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thboileau** [comment]
This issue is not considered as high for two reasons:
 - the response is correctly sent
 - the internal connector is not suggested for production environment. Preferred connectors: the ones based on Jetty, Simple, or servlet container
