### ISSUE TITLE
Swagger extension: java.lang.Object not superclass of org.w3c.dom.Element

### ISSUE THREAD

**Issue by hshorter** [restlet/restlet-framework-java#1011]
I'm getting an exception for version 2.3 of the Swagger extension. It appears the new way the API Doc is built uses the Introspector which can't process interfaces. The full stack is pasted below. The API being used is from the OGF NML Topology model. 

I have also seen the same exception for an RSS feed, where the return type is com.sun.syndication.feed.synd.SyndFeed. Again, this is an interface and cannot be processed by the Introspector, so I think the Swagger extension needs to do something different with interfaces instead of deferring to the Introspector.

```
2015-01-17 00:02:40,440  WARN [Dispatcher: Thread-61] InternalRouter.ResourceApplication.StatusFilter.log():232 - Exception or error caught by status service
java.lang.RuntimeException: Could not get BeanInfo of class org.w3c.dom.Element
	at org.restlet.engine.util.BeanInfoUtils.getBeanInfo(BeanInfoUtils.java:62) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RepresentationCollector.addRepresentation(RepresentationCollector.java:123) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RepresentationCollector.addRepresentation(RepresentationCollector.java:76) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RepresentationCollector.addRepresentation(RepresentationCollector.java:165) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.ResourceCollector.completeOperationOutput(ResourceCollector.java:317) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.ResourceCollector.completeOperation(ResourceCollector.java:190) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.ResourceCollector.collectResourceForServletResource(ResourceCollector.java:124) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collectForFinder(RestletCollector.java:100) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collect(RestletCollector.java:64) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collectForFilter(RestletCollector.java:80) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collect(RestletCollector.java:61) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collectForRoute(RestletCollector.java:116) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collectForRouter(RestletCollector.java:136) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collect(RestletCollector.java:55) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collectForFilter(RestletCollector.java:80) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collect(RestletCollector.java:61) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collectForRoute(RestletCollector.java:116) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collectForRouter(RestletCollector.java:141) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.RestletCollector.collect(RestletCollector.java:55) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.apispark.internal.introspection.application.ApplicationIntrospector.getDefinition(ApplicationIntrospector.java:171) ~[org.restlet.ext.apispark-2.3.0.jar:?]
	at org.restlet.ext.swagger.SwaggerSpecificationRestlet.getDefinition(SwaggerSpecificationRestlet.java:199) ~[org.restlet.ext.swagger-2.3.0.jar:?]
	at org.restlet.ext.swagger.SwaggerSpecificationRestlet.getResourceListing(SwaggerSpecificationRestlet.java:220) ~[org.restlet.ext.swagger-2.3.0.jar:?]
	at org.restlet.ext.swagger.SwaggerSpecificationRestlet.handle(SwaggerSpecificationRestlet.java:246) ~[org.restlet.ext.swagger-2.3.0.jar:?]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.handle(Filter.java:197) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Router.doHandle(Router.java:422) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Router.handle(Router.java:639) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.handle(Filter.java:197) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.handle(Filter.java:197) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.handle(Filter.java:197) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) ~[org.restlet-2.3.0.jar:?]
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:?]
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202) [org.restlet-2.3.0.jar:?]
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75) [org.restlet-2.3.0.jar:?]
	at org.restlet.Application.handle(Application.java:385) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Router.doHandle(Router.java:422) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Router.handle(Router.java:639) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Router.doHandle(Router.java:422) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Router.handle(Router.java:639) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.0.jar:?]
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.0.jar:?]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:?]
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202) [org.restlet-2.3.0.jar:?]
	at org.restlet.Component.handle(Component.java:408) [org.restlet-2.3.0.jar:?]
	at org.restlet.Server.handle(Server.java:507) [org.restlet-2.3.0.jar:?]
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63) [org.restlet-2.3.0.jar:?]
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143) [org.restlet-2.3.0.jar:?]
	at org.restlet.ext.simple.internal.SimpleContainer.handle(SimpleContainer.java:74) [org.restlet.ext.simple-2.3.0.jar:?]
	at org.simpleframework.http.core.Dispatcher.dispatch(Dispatcher.java:121) [simple-5.1.6.jar:?]
	at org.simpleframework.http.core.Dispatcher.run(Dispatcher.java:103) [simple-5.1.6.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110) [?:1.7.0_10]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603) [?:1.7.0_10]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0_10]
Caused by: java.beans.IntrospectionException: java.lang.Object not superclass of org.w3c.dom.Element
	at java.beans.Introspector.<init>(Introspector.java:380) ~[?:1.7.0_10]
	at java.beans.Introspector.getBeanInfo(Introspector.java:250) ~[?:1.7.0_10]
	at org.restlet.engine.util.BeanInfoUtils.getBeanInfo(BeanInfoUtils.java:59) ~[org.restlet-2.3.0.jar:?]
	... 64 more
```

**Comment by thboileau** [comment]
Integrated in RF 2.3.1.
will be available in RF 3.0 snapshot soon
