### ISSUE TITLE
File Upload with large files blocks and stops processing

### ISSUE THREAD

**Issue by johnjaylward** [restlet/restlet-framework-java#1012]
I have an integration test that looks like this:

``` java
final Reference resourceUri = new Reference("http://localhost/customer").addSegment("123")
                .addSegment("location").addSegment("456").addSegment("media");
resourceUri.setBaseRef("http://localhost");
final Request request = new Request(Method.POST, resourceUri);

final FormDataSet fds = new FormDataSet();
fds.setMultipart(true);
if (tags != null) {
    final FormData tagRep = new FormData("tags", new JsonRepresentation(tags));
    fds.getEntries().add(tagRep);
}
if (file != null) {
    final FormData fileRep = new FormData("file", new FileRepresentation(file, mediaType));
    fds.getEntries().add(fileRep);
}

request.setEntity(fds);
final Response resp = this.router.handle(request);
... 
... verify response
... 
```

This works fine for small files, but for one test file I have over 2GB, Restlet appears to lock up in the FileUploadBase.parseRequest method at line 347 : Streams.copy(item.openStream(), fileItem.getOutputStream(), true);

If it's not locking up, it's being extremely slow. Copying the file from one folder to another takes about 2 minutes, however, this doesn't appear to do anything for at least 5 minutes.

**Comment by johnjaylward** [comment]
well, the test case finally completed with a message: HTTP Status was 500 instead of 201. Reason: Unable to read the file sent, please try again.

The total time of execution for the 2GB file before failure was 747 seconds ~12.5 minutes

**Comment by johnjaylward** [comment]
Here is the full stack trace:
```
org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. ./tmp/upload_559b1895_d057_4312_b65b_1bcddf2bb642_00000019.tmp (No such file or directory)
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:351) ~[commons-fileupload-1.3.jar:1.3]
	at org.restlet.ext.fileupload.RestletFileUpload.parseRepresentation(RestletFileUpload.java:113) ~[org.restlet.ext.fileupload-2.3.0.jar:na]
	at mediaserver.resources.MediaResource.create(MediaResource.java:100) ~[bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521) [org.restlet-2.3.0.jar:na]
	at org.restlet.resource.ServerResource.post(ServerResource.java:1376) [org.restlet-2.3.0.jar:na]
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:621) [org.restlet-2.3.0.jar:na]
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679) [org.restlet-2.3.0.jar:na]
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357) [org.restlet-2.3.0.jar:na]
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1044) [org.restlet-2.3.0.jar:na]
	at org.restlet.resource.Finder.handle(Finder.java:236) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Router.doHandle(Router.java:422) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Router.handle(Router.java:639) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.0.jar:na]
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:na]
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202) [org.restlet-2.3.0.jar:na]
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75) [org.restlet-2.3.0.jar:na]
	at org.restlet.Application.handle(Application.java:385) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.doHandle(Filter.java:150) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Filter.handle(Filter.java:197) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Router.doHandle(Router.java:422) [org.restlet-2.3.0.jar:na]
	at org.restlet.routing.Router.handle(Router.java:639) [org.restlet-2.3.0.jar:na]
	at org.restlet.Restlet.handle(Restlet.java:275) [org.restlet-2.3.0.jar:na]
	at mediaserver.resources.MediaResourceTest.create(MediaResourceTest.java:248) [bin/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84) [testng.jar:6.8.7beta-201309140723]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714) [testng.jar:6.8.7beta-201309140723]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901) [testng.jar:6.8.7beta-201309140723]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231) [testng.jar:6.8.7beta-201309140723]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) [testng.jar:6.8.7beta-201309140723]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) [testng.jar:6.8.7beta-201309140723]
	at org.testng.TestRunner.privateRun(TestRunner.java:767) [testng.jar:6.8.7beta-201309140723]
	at org.testng.TestRunner.run(TestRunner.java:617) [testng.jar:6.8.7beta-201309140723]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334) [testng.jar:6.8.7beta-201309140723]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329) [testng.jar:6.8.7beta-201309140723]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291) [testng.jar:6.8.7beta-201309140723]
	at org.testng.SuiteRunner.run(SuiteRunner.java:240) [testng.jar:6.8.7beta-201309140723]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng.jar:6.8.7beta-201309140723]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng.jar:6.8.7beta-201309140723]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224) [testng.jar:6.8.7beta-201309140723]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149) [testng.jar:6.8.7beta-201309140723]
	at org.testng.TestNG.run(TestNG.java:1057) [testng.jar:6.8.7beta-201309140723]
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111) [testng.jar:6.8.7beta-201309140723]
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204) [testng.jar:6.8.7beta-201309140723]
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175) [testng.jar:6.8.7beta-201309140723]
Caused by: java.io.FileNotFoundException: ./tmp/upload_559b1895_d057_4312_b65b_1bcddf2bb642_00000019.tmp (No such file or directory)
	at java.io.FileOutputStream.open(Native Method) ~[na:1.8.0_25]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_25]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_25]
	at org.apache.commons.io.output.DeferredFileOutputStream.thresholdReached(DeferredFileOutputStream.java:178) ~[commons-io-2.2.jar:2.2]
	at org.apache.commons.io.output.ThresholdingOutputStream.checkThreshold(ThresholdingOutputStream.java:224) ~[commons-io-2.2.jar:2.2]
	at org.apache.commons.io.output.ThresholdingOutputStream.write(ThresholdingOutputStream.java:128) ~[commons-io-2.2.jar:2.2]
	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:108) ~[commons-fileupload-1.3.jar:1.3]
	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:70) ~[commons-fileupload-1.3.jar:1.3]
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:347) ~[commons-fileupload-1.3.jar:1.3]
	... 59 common frames omitted
```

**Comment by thboileau** [comment]
Hi @johnjaylward, could you precise the version of RF and the edition (jse, jee, gae, etc)?

**Comment by johnjaylward** [comment]
Restlet JSE 2.3.0 from the maven repo. I'm also including (using gradle):
    compile group: "org.restlet.jse", name: "org.restlet.ext.json", version: "2.3.0"
    compile group: "org.restlet.jse", name: "org.restlet.ext.fileupload", version: "2.3.0"
    compile group: "org.restlet.jse", name: "org.restlet.ext.guice", version: "2.3.0"
    compile group: "com.google.inject", name: "guice", version: "3.0"

**Comment by thboileau** [comment]
I've made a test with a server resource, that copies the incoming stream into `/tmp/dest.txt`.
Then, on client side I send a 3000*1mb file using curl or restlet client (in distinct jvm).

I've got the following results:
client | server connector | result
--------|-----------------------|--------
curl | internal connector | 12 sec
restlet internal connector | internal connector | 16 sec
curl | Jetty extension | 10sec
Jetty extension | Jetty extension | error



Error trace on client side (Jetty extension): 
```
java.util.concurrent.TimeoutException
	at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:226)
	at org.restlet.ext.jetty.internal.JettyClientCall.sendRequest(JettyClientCall.java:275)
	at org.restlet.engine.adapter.ClientAdapter.commit(ClientAdapter.java:105)
	at org.restlet.engine.adapter.HttpClientHelper.handle(HttpClientHelper.java:119)
	at org.restlet.Client.handle(Client.java:153)
	at org.restlet.Restlet.handle(Restlet.java:275)
	at testFileUpload.MyClient.main(MyClient.java:36)
Error while writing to the piped input stream.

java.io.IOException: Timeout while writing to the queue-based output stream
	at org.restlet.engine.io.PipeStream$2.write(PipeStream.java:99)
	at java.io.OutputStream.write(OutputStream.java:116)
	at org.restlet.engine.io.IoUtils.copy(IoUtils.java:98)
	at org.restlet.representation.FileRepresentation.write(FileRepresentation.java:261)
	at org.restlet.ext.html.FormDataSet.write(FormDataSet.java:314)
	at org.restlet.engine.io.IoUtils$3.run(IoUtils.java:576)
	at org.restlet.engine.Engine$1.run(Engine.java:166)
	at java.lang.Thread.run(Thread.java:745)
Error while closing the pipe.

java.io.IOException: Timeout while writing to the queue-based output stream
	at org.restlet.engine.io.PipeStream$2.close(PipeStream.java:112)
	at org.restlet.engine.io.IoUtils$3.run(IoUtils.java:584)
	at org.restlet.engine.Engine$1.run(Engine.java:166)
	at java.lang.Thread.run(Thread.java:745)
```

Error trace on server side Jetty extension:
```
Internal Server Error (500) - The server encountered an unexpected condition which prevented it from fulfilling the request
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:540)
	at org.restlet.resource.ServerResource.post(ServerResource.java:1376)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:621)
	at org.restlet.resource.ServerResource.doNegotiatedHandle(ServerResource.java:679)
	at org.restlet.resource.ServerResource.doConditionalHandle(ServerResource.java:357)
	at org.restlet.resource.ServerResource.handle(ServerResource.java:1044)
	at org.restlet.resource.Finder.handle(Finder.java:236)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.jetty.JettyServerHelper$WrappedServer.handle(JettyServerHelper.java:273)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:313)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:626)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:546)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.jetty.io.EofException: Early EOF
	at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:492)
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:124)
	at org.apache.commons.fileupload.MultipartStream$ItemInputStream.makeAvailable(MultipartStream.java:997)
	at org.apache.commons.fileupload.MultipartStream$ItemInputStream.read(MultipartStream.java:901)
	at java.io.InputStream.read(InputStream.java:101)
	at org.restlet.engine.io.IoUtils.copy(IoUtils.java:97)
	at testFileUpload.HelloResource.accept(HelloResource.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:521)
	... 47 more
```
```
```

**Comment by thboileau** [comment]
There seem to be several issues with the Jetty's client connector.
 - there is no way to configure the buffer size of the instance of the `InputStreamContentProvider` used to read from the file input stream (cf class `JettyClientCall`)
 - the idleTimeout seems short enough (though its default value is 60 sec) to cut the connection, but at the same time, I still see some content sent by the jetty client.

**Comment by jlouvel** [comment]
Closing this issue as the FileUpload extension has been removed in 2.7 branch. Look at the MultipartRepresentation class in Restlet API moving forward, based on Jetty.
