### ISSUE TITLE
ClientProxy breaks when Bean is annoated for GWT Bean validation

### ISSUE THREAD

**Issue by kerbymart** [restlet/restlet-framework-java#1020]
**How to reproduce:**

In a working ClientProxy resource, add GWT Bean Validation like this:

@HasRequiredStuffValues(groups = DraftValidationGroup.class, message = "Please enter the required fields")
public class StuffItemDTO implements Serializable {
    @NotEmpty(groups = DraftValidationGroup.class, message = "Please enter content")
    private String content;
}

Now this StuffItemDTO cannot be sent to Restlet server-side, throwing:

INFO] java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
....some stacktrace omitted...
com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter$ValueWriter$8.write(ServerSerializationStreamWriter.java:153)
[INFO]  at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeValue(ServerSerializationStreamWriter.java:587)
[INFO]  at org.restlet.ext.gwt.ObjectRepresentation.getText(ObjectRepresentation.java:162)

**Expected:**

There should be no problem at all. The ClientProxy should work the same like when it was without bean validation

**Comment by komasoftware** [comment]
Did you add 
 - hibernate-validator-4.2.0.Final-sources.jar
 - hibernate-validator-4.2.0.Final.jar
to your project ?

Did you check whether serialization works with plain GWT-RPC ?

**Comment by kerbymart** [comment]
@thboileau Is this a Restlet bug? Or could be something else?

@komasoftware yes Hibernate validator is there, also Bean Validation works just right in client side, so my idea is this is a serialization bug of Restlet...

**Comment by komasoftware** [comment]
@kerbymart I am using bean validation with Restlet and GWT, works fine. So the problem must be in your setup IMO.

**Comment by komasoftware** [comment]
Is your custom bean validation @HasRequiredStuffValues in the shared source path for GWT ?

**Comment by kerbymart** [comment]
Yes indeed. 
com.mycompany.client.entity.StuffItemDTO
com.mycompany.client.shared.validation.constraint.HasRequiredStuffValues

Without the annotations, the StuffItemDTO works fine with ClientProxy.
Adding the annotations breaks the same working code (no changes in the client resource or whatsoever)

**Comment by komasoftware** [comment]
@kerbymart  Maybe you used non-translatable classes in the implementation of your custom validation annotation, e.g. Calendar.

**Comment by kerbymart** [comment]
Hmm not that I am aware of,

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

the constraints have these

**Comment by thboileau** [comment]
Hi @kerbymart, this is not very easy to investigate this issue.
Are you able to isolate the cause of the exception, is it the HasRequiredStuffValues, or the NotEmpty annotation?
Can you provide a sample test case?

**Comment by thboileau** [comment]
linked to SOF question: http://stackoverflow.com/questions/28271860/bean-validation-annotation-breaks-reslet-clientproxy/28317929

**Comment by kerbymart** [comment]
@thboileau I think I finally figured out the problem (but not fixed it yet). At first I was using jackson, so I switched to XStream. Now the same TypeNotPresentExceptionProxy is being thrown. Having said this, its not totally about bean validation, but rather annotation processing that breaks. Where the bean validation annotation is in the client/shared package of GWT. It looks to me that annotation are not serialized by the Restlet mechanism.

**Comment by kerbymart** [comment]
Here is another log using Restlet 2.3.1 and XStream extension:

[INFO] java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
[INFO] 	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
[INFO] 	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
[INFO] 	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
[INFO] 	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
[INFO] 	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
[INFO] 	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
[INFO] 	at java.lang.reflect.Field.declaredAnnotations(Field.java:1140)
[INFO] 	at java.lang.reflect.Field.getAnnotation(Field.java:1114)
[INFO] 	at com.thoughtworks.xstream.mapper.AnnotationMapper.processFieldAliasAnnotation(AnnotationMapper.java:390)
[INFO] 	at com.thoughtworks.xstream.mapper.AnnotationMapper.processTypes(AnnotationMapper.java:218)
[INFO] 	at com.thoughtworks.xstream.mapper.AnnotationMapper.processAnnotations(AnnotationMapper.java:174)
[INFO] 	at com.thoughtworks.xstream.mapper.AnnotationMapper.serializedClass(AnnotationMapper.java:125)
[INFO] 	at com.thoughtworks.xstream.mapper.MapperWrapper.serializedClass(MapperWrapper.java:26)
[INFO] 	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:80)
[INFO] 	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
[INFO] 	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1022)
[INFO] 	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1011)
[INFO] 	at com.thoughtworks.xstream.XStream.toXML(XStream.java:984)
[INFO] 	at org.restlet.ext.xstream.XstreamRepresentation.write(XstreamRepresentation.java:299)
[INFO] 	at org.restlet.representation.CharacterRepresentation.write(CharacterRepresentation.java:67)
[INFO] 	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:510)
[INFO] 	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:454)
[INFO] 	at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:453)
[INFO] 	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:187)
[INFO] 	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
[INFO] 	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
[INFO] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
[INFO] 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
[INFO] 	at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:127)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectRequest(DevAppServerModulesFilter.java:366)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doDirectModuleRequest(DevAppServerModulesFilter.java:349)
[INFO] 	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:116)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
[INFO] 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
[INFO] 	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
[INFO] 	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
[INFO] 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
[INFO] 	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
[INFO] 	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:98)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:491)
[INFO] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
[INFO] 	at org.mortbay.jetty.Server.handle(Server.java:326)
[INFO] 	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
[INFO] 	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
[INFO] 	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
[INFO] 	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
[INFO] 	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
[INFO] 	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
[INFO] 	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by jlouvel** [comment]
Closing this issue as the GWT edition has been removed in 2.7 branch.
