### ISSUE TITLE
java.io.FileNotFoundException when trying to serve static content

### ISSUE THREAD

**Issue by sansjunk** [restlet/restlet-framework-java#1049]
I am running into an issue when trying to serve up some static files along with an API using Restlet 2.3.1 for JEE. I am not sure if it's something I am not doing right or its something in Restlet.

My project is configured as a webapp (WAR) and is run by Tomcat. Here is the code I have setup for serving up files:

```java
public Restlet createInboundRoot()
{
   ...
   Directory directory = new Directory(getContext(), "war:///assets");
   router.attach("/assets", directory);
   ...
}
```

I have the following folder structure in my WAR:
```
assets
    assets\css
    assets\css\default.theme.css
META-INF
templates
WEB-INF
```

When I run in Eclipse (using Tomcat as the container) and try to navigate to `http://localhost/myapp/v1/assets/css` I get a HTTP 500 (internal server error) due to the following exception from Resetlet:

```
INFO: 2015-03-31	11:14:57	192.168.10.108	-	192.168.10.108	3000	GET	/stardocs/v1/assets/css	-	500	486	0	39	http://localhost:3000	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.95 Safari/537.36	-
Mar 31, 2015 11:31:27 AM org.restlet.ext.servlet.internal.ServletWarEntity getRepresentation
WARNING: Error getting the WAR resource.
java.io.FileNotFoundException: jndi:/localhost/myapp/assets/
	at org.apache.naming.resources.DirContextURLConnection.getInputStream(DirContextURLConnection.java:389)
	at org.restlet.ext.servlet.internal.ServletWarEntity.getRepresentation(ServletWarEntity.java:179)
	at org.restlet.engine.local.EntityClientHelper.handleEntityGet(EntityClientHelper.java:277)
	at org.restlet.engine.local.EntityClientHelper.handleLocal(EntityClientHelper.java:301)
	at org.restlet.ext.servlet.internal.ServletWarClientHelper.handleLocal(ServletWarClientHelper.java:101)
	at org.restlet.engine.local.LocalClientHelper.handle(LocalClientHelper.java:122)
	at org.restlet.ext.servlet.internal.ServletWarClient.handle(ServletWarClient.java:87)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.engine.component.ComponentClientDispatcher.doHandle(ComponentClientDispatcher.java:129)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.util.ChildClientDispatcher.parentHandle(ChildClientDispatcher.java:139)
	at org.restlet.engine.util.ChildClientDispatcher.doHandle(ChildClientDispatcher.java:112)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.Restlet.handle(Restlet.java:275)
	at org.restlet.engine.local.DirectoryServerResource.getRepresentation(DirectoryServerResource.java:499)
	at org.restlet.engine.local.DirectoryServerResource.doInit(DirectoryServerResource.java:343)
	at org.restlet.resource.Resource.init(Resource.java:767)
	at org.restlet.resource.Finder.handle(Finder.java:233)
	at org.restlet.resource.Directory.handle(Directory.java:238)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Mar 31, 2015 11:31:27 AM org.restlet.resource.ServerResource doCatch
WARNING: Exception or error caught in server resource
java.lang.NullPointerException
	at org.restlet.engine.local.EntityClientHelper.handleEntityGet(EntityClientHelper.java:280)
	at org.restlet.engine.local.EntityClientHelper.handleLocal(EntityClientHelper.java:301)
	at org.restlet.ext.servlet.internal.ServletWarClientHelper.handleLocal(ServletWarClientHelper.java:101)
	at org.restlet.engine.local.LocalClientHelper.handle(LocalClientHelper.java:122)
	at org.restlet.ext.servlet.internal.ServletWarClient.handle(ServletWarClient.java:87)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.engine.component.ComponentClientDispatcher.doHandle(ComponentClientDispatcher.java:129)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.util.ChildClientDispatcher.parentHandle(ChildClientDispatcher.java:139)
	at org.restlet.engine.util.ChildClientDispatcher.doHandle(ChildClientDispatcher.java:112)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.Restlet.handle(Restlet.java:275)
	at org.restlet.engine.local.DirectoryServerResource.getRepresentation(DirectoryServerResource.java:499)
	at org.restlet.engine.local.DirectoryServerResource.doInit(DirectoryServerResource.java:343)
	at org.restlet.resource.Resource.init(Resource.java:767)
	at org.restlet.resource.Finder.handle(Finder.java:233)
	at org.restlet.resource.Directory.handle(Directory.java:238)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
Note that if I try to navigate to `http://localhost/myapp/v1/assets/css/default.theme.css` then restlet doesn't throw an exception but returns HTTP 404 which isn't what's expected.

**Comment by thboileau** [comment]
Hi @sansjunk , I've made a simple test and it works for me.
I use RF 2.3.1, tomcat 7.0.53, jdk 1.7.0_80, and eclipse kepler.

![java - test-src-test-myapplication java - eclipse - -home-thboileau-workspace-restlet-2 3 _024](https://cloud.githubusercontent.com/assets/1122782/7204104/ed1fea5e-e51f-11e4-8163-bd37bc731d67.png)

**Comment by sansjunk** [comment]
More details:
Restlet: 2.3.1
Tomcat: Upgraded to 7.0.61
JRE: 1.8.0_40

**Case 1: Running in Eclipse Luna Service Release 2 (4.4.2)**
I am not seeing the exception anymore after upgrading Tomcat from 7.0.52, however I am getting a 404 when trying to fetch the files. See screenshot below:

![running_in_eclipse](https://cloud.githubusercontent.com/assets/1901231/7268418/cebd96cc-e8e6-11e4-8de0-57936e5e9964.jpg)

**Case 2: Deployed as WAR in Tomcat**
Here the file is getting served however the complete transfer to the browser is taking minutes! See screenshot below:

![deployed_as_war](https://cloud.githubusercontent.com/assets/1901231/7268420/dbfc36ea-e8e6-11e4-911d-6f9dc9a19693.jpg)

**Comment by thboileau** [comment]
Thanks a lot for the details.

**Comment by thboileau** [comment]
Hi @sansjunk , here is my sample code (eclipse project). Could you check it? https://restlet.com/technical-resources/restlet-framework/archives/misc/2.3/testjee.zip

**Comment by sansjunk** [comment]
Sorry for getting back late on this. I am not able to find the zip file, has the link expired?

**Comment by thboileau** [comment]
Hi @sansjunk , my bad, I've recovered the file, it is now available.

**Comment by sansjunk** [comment]
Hi @thboileau thanks for the sample code - it helped me track down the issue which was being caused by an old version of Tomcat library being used in the project (catalina.jar). After updating to the latest version of the library the exception is not happening anymore and the static files are being served correctly. Thanks for the support, I'll be closing this issue.
