### ISSUE TITLE
Swagger Ext in WildFly8.2 problem

### ISSUE THREAD

**Issue by wody** [restlet/restlet-framework-java#1058]
Using the (jee) swagger extension in Restlet 2.3.1 leads me to a deploy error in WildFly 8.2:

```
Caused by: org.jboss.weld.exceptions.DefinitionException: WELD-000075: Normal scoped managed bean implementation class has a public field:  [EnhancedAnnotatedFieldImpl] public org.restlet.ext.jaxrs.internal.provider.JaxbProvider.contextResolver
	at org.jboss.weld.bean.ManagedBean.checkBeanImplementation(ManagedBean.java:218)
	at org.jboss.weld.bean.AbstractClassBean.internalInitialize(AbstractClassBean.java:74)
	at org.jboss.weld.bean.ManagedBean.internalInitialize(ManagedBean.java:96)
	at org.jboss.weld.bean.RIBean.initialize(RIBean.java:66)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$5.doWork(ConcurrentBeanDeployer.java:121)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$5.doWork(ConcurrentBeanDeployer.java:118)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:60)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:53)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_80]
	... 3 more
```
Is this a known issue?

**Comment by thboileau** [comment]
I see that the `contextResolver` property of the `JaxbProvider` is public. I fix this issue.

**Comment by thboileau** [comment]
Thanks a lot for reporting this issue.
I've fixed the 2.3 branch, I will synchronize the master branch soon.
2.3.2 version will be available at the end of this week.

**Comment by wody** [comment]
Thanks a lot for addressing the issue that fast.

**Comment by wody** [comment]
I can confirm this is now working with the current 2.3.2 version

**Comment by jlouvel** [comment]
Thanks for the follow-up @wody
