### ISSUE TITLE
Template (thymeleaf) parse error produces never ending request (headers already sent)

### ISSUE THREAD

**Issue by notz** [restlet/restlet-framework-java#1061]
Connection should be closed on IO Exception.

```
[ERROR] Restlet-1925314656 org.thymeleaf.TemplateEngine:1085 process 
[THYMELEAF][Restlet-1925314656] Exception processing template "index": Exception parsing document: template="index", line 76 - column 4
Unable to process the template

org.thymeleaf.exceptions.TemplateInputException: Exception parsing document: template="index", line 76 - column 4
	at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplateUsingPool(AbstractNonValidatingSAXTemplateParser.java:167)
	at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplate(AbstractNonValidatingSAXTemplateParser.java:117)
	at org.thymeleaf.TemplateRepository.getTemplate(TemplateRepository.java:277)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1104)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:955)
	at org.restlet.ext.thymeleaf.TemplateRepresentation.write(TemplateRepresentation.java:377)
	at org.restlet.representation.CharacterRepresentation.write(CharacterRepresentation.java:67)
	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:510)
	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:454)
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:187)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
	at org.restlet.engine.connector.HttpServerHelper$1.handle(HttpServerHelper.java:64)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:677)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:649)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXParseException; lineNumber: 76; columnNumber: 4; The element type "meta" must be terminated by the matching end-tag "</meta>".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1749)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:332)
	at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.doParse(AbstractNonValidatingSAXTemplateParser.java:210)
	at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplateUsingPool(AbstractNonValidatingSAXTemplateParser.java:134)
	... 22 more
org.thymeleaf.exceptions.TemplateInputException: Exception parsing document: template="index", line 76 - column 4
	at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplateUsingPool(AbstractNonValidatingSAXTemplateParser.java:167)
	at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplate(AbstractNonValidatingSAXTemplateParser.java:117)
	at org.thymeleaf.TemplateRepository.getTemplate(TemplateRepository.java:277)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1104)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:955)
	at org.restlet.ext.thymeleaf.TemplateRepresentation.write(TemplateRepresentation.java:377)
	at org.restlet.representation.CharacterRepresentation.write(CharacterRepresentation.java:67)
	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:510)
	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:454)
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:187)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
	at org.restlet.engine.connector.HttpServerHelper$1.handle(HttpServerHelper.java:64)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:677)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:649)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXParseException; lineNumber: 76; columnNumber: 4; The element type "meta" must be terminated by the matching end-tag "</meta>".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1749)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:332)
	at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.doParse(AbstractNonValidatingSAXTemplateParser.java:210)
	at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplateUsingPool(AbstractNonValidatingSAXTemplateParser.java:134)
	... 22 more
An exception occured writing the response entity

java.io.IOException: Template processing error. Exception parsing document: template="index", line 76 - column 4
	at org.restlet.ext.thymeleaf.TemplateRepresentation.write(TemplateRepresentation.java:390)
	at org.restlet.representation.CharacterRepresentation.write(CharacterRepresentation.java:67)
	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:510)
	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:454)
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:187)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
	at org.restlet.engine.connector.HttpServerHelper$1.handle(HttpServerHelper.java:64)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:677)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:649)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Unable to send error response

java.io.IOException: headers already sent
	at sun.net.httpserver.ExchangeImpl.sendResponseHeaders(ExchangeImpl.java:204)
	at sun.net.httpserver.HttpExchangeImpl.sendResponseHeaders(HttpExchangeImpl.java:86)
	at org.restlet.engine.connector.HttpExchangeCall.writeResponseHead(HttpExchangeCall.java:161)
	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:450)
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:205)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144)
	at org.restlet.engine.connector.HttpServerHelper$1.handle(HttpServerHelper.java:64)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:677)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:649)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by notz** [comment]
ServerCall should look like this:

```
OutputStream responseEntityStream = null;

            try {
                writeResponseHead(response);

                if (responseEntity != null) {
                    responseEntityStream = getResponseEntityStream();
                    writeResponseBody(responseEntity, responseEntityStream);
                }
            } finally {

                if (responseEntityStream != null) {
                    try {
                        responseEntityStream.flush();
                        responseEntityStream.close();
                    } catch (IOException ioe) {
                        // The stream was probably already closed by the
                        // connector. Probably OK, low message priority.
                        getLogger()
                                .log(Level.FINE,
                                        "Exception while flushing and closing the entity stream.",
                                        ioe);
                    }
                }

                if (responseEntity != null) {
                    responseEntity.release();
                }

                if (connectorService != null) {
                    connectorService.afterSend(responseEntity);
                }
            }
```

ServerAdapter should not try to send Error Header after writing Response fails. It will never work, writing again Headers.

**Comment by thboileau** [comment]
Thanks for reporting this issue. I see several issues, the one you point (never ending request), the fact that the error response cannot be sent properly (message `headers already sent`).

For a production environment, I suggest, as a side note and not as a workaround, to use another server connector (such as the one based on Jetty `org.restlet.ext.jetty`, or simple `org.restlet.ext.simple`). Your code won't change at all, just update the classpath in order to add the extension ans its dependency.

**Comment by thboileau** [comment]
Hi @notz ,

do you mind signing the JCA (https://github.com/restlet/restlet-framework-java/wiki/Contribute#submit-contributions) and send it back to us (contact@restlet.com)? It will allow me to integrate your contribution.

Best regards,
Thierry Boileau

**Comment by thboileau** [comment]
Hi @notz ,
thanks for the JCA, I've integrated the fix for the never ending call issue.
