### ISSUE TITLE
OAuth refresh token request without scope throws a NPE

### ISSUE THREAD

**Issue by notz** [restlet/restlet-framework-java#1080]
```
Caused by: java.lang.NullPointerException
        at java.util.Objects.requireNonNull(Objects.java:203)
        at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
        at java.util.Arrays.asList(Arrays.java:3800)
        at org.restlet.ext.oauth.internal.Scopes.isIdentical(Scopes.java:43)
        at org.restlet.ext.oauth.AccessTokenServerResource.responseTokenRepresentation(AccessTokenServerResource.java:462)
        at org.restlet.ext.oauth.AccessTokenServerResource.doRefreshFlow(AccessTokenServerResource.java:263)
        at org.restlet.ext.oauth.AccessTokenServerResource.requestToken(AccessTokenServerResource.java:431)
```

The scope should be always included if the requested scope is null in AccessTokenServerResource.requestToken.

```java
if (requestedScope == null || !Scopes.isIdentical(scope, requestedScope)) {
    response.put("scope", Scopes.toString(scope));
}
```

**Comment by thboileau** [comment]
Hi @notz, thanks a lot for reporting this issue, it is now part of 2.3 and 3.0 branches.
