### ISSUE TITLE
java.lang.ClassCastException: org.restlet.data.Parameter cannot be cast to org.restlet.data.Header

### ISSUE THREAD

**Issue by ernotorok** [restlet/restlet-framework-java#1143]
I've seen a similar report, that was caused by the side effect of a CORS filter. Here a servlet filter is also involved, but all Restlet calls are from the 2.3.1 jar, and I do not have any other version in my war.
Could you see how Parameter gets involvedd?

java.lang.ClassCastException: org.restlet.data.Parameter cannot be cast to org.restlet.data.Header
	at org.restlet.engine.header.HeaderUtils.addExtensionHeaders(HeaderUtils.java:220) ~[org.restlet-2.3.1.jar:na]
	at org.restlet.engine.header.HeaderUtils.addResponseHeaders(HeaderUtils.java:641) ~[org.restlet-2.3.1.jar:na]
	at org.restlet.engine.adapter.ServerAdapter.addResponseHeaders(ServerAdapter.java:83) [org.restlet-2.3.1.jar:na]
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:184) [org.restlet-2.3.1.jar:na]
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:144) [org.restlet-2.3.1.jar:na]
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117) [org.restlet.ext.servlet-2.3.1.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:751) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1666) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at com.sonymobile.common.LogServletFilter.doFilter(LogServletFilter.java:28) [common-5.5.7-SNAPSHOT.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1645) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:564) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.sersion.SessionHandler.doHandle(SessionHandler.java:221) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:498) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.server.Server.handle(Server.java:461) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536) [connect-5.5.7-SNAPSHOT.war:5.5.7-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]

**Comment by ernotorok** [comment]
The error was caused by our code, when we set a response header now of type Series<Header>, it was Form before.
