### ISSUE TITLE
Cannot consume restlet.ext.jaxrs 2.3 in OSGI application: java.lang.NoClassDefFoundError: org/simpleframework/xml/Serializer

### ISSUE THREAD

**Issue by abstratt** [restlet/restlet-framework-java#1174]
Due to #640 (which apparently also happens in 2.2) I am trying to move to Restlet 2.3.

However, it seems some of the Restlet JARs have OSGi dependencies on at least one dependency that does not seem to be available as an OSGi bundle: org.simpleframework.web, required by org.restlet.ext.jaxrs. The result is a NoClassDefFoundError:

```
java.lang.NoClassDefFoundError: org/simpleframework/xml/Serializer
    at org.restlet.ext.jaxrs.JaxRsRestlet.loadDefaultProviders(JaxRsRestlet.java:1066)
    at org.restlet.ext.jaxrs.JaxRsRestlet.<init>(JaxRsRestlet.java:228)
    at org.restlet.ext.jaxrs.JaxRsApplication.<init>(JaxRsApplication.java:88)
    at org.restlet.ext.jaxrs.JaxRsApplication.<init>(JaxRsApplication.java:75)
    at com.abstratt.kirra.mdd.rest.impl.v2.KirraOnMDDRestletApplication.<init>(KirraOnMDDRestletApplication.java:20)
    at com.abstratt.kirra.mdd.rest.impl.v2.KirraRESTServlet.createApplication(KirraRESTServlet.java:13)
    at org.restlet.ext.servlet.ServerServlet.getApplication(ServerServlet.java:802)
    at org.restlet.ext.servlet.ServerServlet.createServer(ServerServlet.java:538)
    at org.restlet.ext.servlet.ServerServlet.getServer(ServerServlet.java:945)
    at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1114)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

As a side note, for some reason I can only see (using p2-enabled tools) up to version 2.3.2.v20150501-1520 under http://p2.restlet.com/2.3/, though there are more recent jars in the directory structure.

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
