### ISSUE TITLE
NPE if using Redirector.MODE_SERVER_INBOUND

### ISSUE THREAD

**Issue by mpdeimos** [restlet/restlet-framework-java#1182]
I'm getting the `NullPointerException` if I am using `Redirector` with `MODE_SERVER_INBOUND` in order to create an alias for a resource:
```
java.lang.NullPointerException
	at org.restlet.engine.component.HostRoute.score(HostRoute.java:163)
	at org.restlet.util.RouteList.getFirst(RouteList.java:115)
	at org.restlet.routing.Router.getNext(Router.java:540)
	at org.restlet.routing.Router.handle(Router.java:636)
	at org.restlet.engine.component.ComponentServerDispatcher.doHandle(ComponentServerDispatcher.java:71)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Redirector.serverRedirect(Redirector.java:518)
	at org.restlet.routing.Redirector.inboundServerRedirect(Redirector.java:358)
	at org.restlet.routing.Redirector.handle(Redirector.java:337)
```

This is the sample code I used:

```java
public class MyServer extends Application {
	@Override
	public Restlet createInboundRoot() {
		Router router = new Router(getContext());
		router.attach("/foo", TestResource.class);
		router.attach("/index.html", new Redirector(getContext(), "/prefix/foo", Redirector.MODE_SERVER_INBOUND));
		return router;
	}

	public static void main(String[] args) throws Exception {
		Component component = new Component();
		component.getServers().add(Protocol.HTTP, 8182);
		component.getDefaultHost().attach("/prefix", new MyServer());
		component.start();
	}
}
```

I guess the NPE is thrown because the protocol is explicitly set to `null` in the `Redirector` class, see: https://github.com/restlet/restlet-framework-java/blame/master/modules/org.restlet/src/org/restlet/routing/Redirector.java#L513

The above example is a minimal one. What I want to achieve is having an alias for a resource served from a directory that is normally accessible via the path `/static/html/index.html`. The aliases should be `/ -> /static/html/index.html` and `index.html -> /static/html/index.html`.
Maybe I'm also doing something fundamentally wrong, but coding the alias/rewrite by hand works:
```java
		router.attach("/index.html", new Restlet(getContext()) {
			@Override
			public void handle(Request request, Response response) {
				request.getResourceRef().setPath("/prefix/foo");
				getContext().getServerDispatcher().handle(request, response);
			}
		});
```

**Comment by thboileau** [comment]
Hi,
you can code the redirection using the [http://restlet.com/technical-resources/restlet-framework/guide/2.3/core/engine/internal-connectors/riap](RIAP) protocol as follow
```java
        router.attach("/index.html", new Redirector(getContext(), "riap://application/foo"));
```

**Comment by mpdeimos** [comment]
Hi,
The workaround works for me. Thanks.

**Comment by thboileau** [comment]
Hi @mpdeimos, I've added a fix that prevents the NPE. As there is still an issue, I need to discuss one with @jlouvel .

**Comment by thboileau** [comment]
Hi @jlouvel to you have time to discuss this issue?
