### ISSUE TITLE
Severe error on parsing the Warning HTTP Header

### ISSUE THREAD

**Issue by PedroD** [restlet/restlet-framework-java#1184]
I found what appears to be a severe error of RESTLET parsing headers.

It seems easy to reproduce, you just need to make a call to a REST endpoint which answers with the HTTP warning header containing the following value:

`Warning: 400 "Key not found in request!"`

Restlet will mistakenly parse the string within double quotes and throw an exception as you can see:

http://i.imgur.com/jIdZAI7.png

http://i.imgur.com/paSYbDl.png

So when it reaches [this](http://i.imgur.com/RA7vrVt.png) line he won't read a quoted string.

	java.io.IOException: A quoted string must start with a double quote
		at org.restlet.engine.header.HeaderReader.readQuotedString(HeaderReader.java:552)
		at org.restlet.engine.header.WarningReader.readValue(WarningReader.java:72)
		at org.restlet.engine.header.WarningReader.readValue(WarningReader.java:40)
		at org.restlet.engine.header.HeaderReader.addValues(HeaderReader.java:282)
		at org.restlet.engine.header.WarningReader.addValues(WarningReader.java:51)
		at org.restlet.engine.header.HeaderUtils.copyResponseTransportHeaders(HeaderUtils.java:773)
		at org.restlet.engine.adapter.ClientAdapter.readResponseHeaders(ClientAdapter.java:129)
		at org.restlet.engine.adapter.ClientAdapter.updateResponse(ClientAdapter.java:191)
		at org.restlet.engine.adapter.ClientAdapter.commit(ClientAdapter.java:105)
		at org.restlet.engine.adapter.HttpClientHelper.handle(HttpClientHelper.java:119)
		at org.restlet.Client.handle(Client.java:153)
		at org.restlet.routing.Filter.doHandle(Filter.java:150)
		at org.restlet.routing.Filter.handle(Filter.java:197)
		at org.restlet.resource.ClientResource.handle(ClientResource.java:1092)
		at org.restlet.resource.ClientResource.handleOutbound(ClientResource.java:1176)
		at org.restlet.resource.ClientResource.handle(ClientResource.java:1047)
		at org.restlet.resource.ClientResource.handle(ClientResource.java:1065)
		at org.restlet.resource.ClientResource.post(ClientResource.java:1466)

You can quickly reproduce this error by mounting a mock HTTP endpoint which returns anything, but contains the text `400 "Key not found in request!"` in its warning header. For example:

http://i.imgur.com/VWD85ja.png

I am using RESTLET 3.0-M1.

According to the HTTP Headers specs, the warning header is arbitrary so RESTLET should not expect it to be of a given way (quoted string and all).

Can this be fixed soon?

Thanks!

**Comment by thboileau** [comment]
Hello @PedroD 
I feel really sorry to answer so lately to your request.
Having read the 2616 and the 7234 RFC's (the latter obsoletes the former), I understand that the Warning header is not arbitrary, but instead must complies with a specific [pattern](https://tools.ietf.org/html/rfc7234#section-5.5).

In your case, the Warning header lacks the warn-agent piece of data.
What is your thinking about this?

Again, all my apologies for the delay.
