### ISSUE TITLE
Please add support for newest JAXRS api.

### ISSUE THREAD

**Issue by theprivateland** [restlet/restlet-framework-java#1204]
I get:

```
java.lang.AbstractMethodError: javax.ws.rs.core.Response.getStatusInfo()Ljavax/ws/rs/core/Response$StatusType;
    at javax.ws.rs.WebApplicationException.computeExceptionMessage(WebApplicationException.java:211)
    at javax.ws.rs.WebApplicationException.<init>(WebApplicationException.java:185)
    at javax.ws.rs.WebApplicationException.<init>(WebApplicationException.java:90)
    at org.restlet.ext.jaxrs.internal.util.ExceptionHandler.methodNotAllowed(ExceptionHandler.java:218)
    at org.restlet.ext.jaxrs.JaxRsRestlet.identifyMethod(JaxRsRestlet.java:860)
    at org.restlet.ext.jaxrs.JaxRsRestlet.requestMatching(JaxRsRestlet.java:1171)
    at org.restlet.ext.jaxrs.JaxRsRestlet.handle(JaxRsRestlet.java:742)
    at org.restlet.routing.Filter.doHandle(Filter.java:150)
    at org.restlet.routing.Filter.handle(Filter.java:197)

```

This basically means that jaxrs api is not matching implementation, can you update it?

WebApplicationException  is default exception thrown in framework.

I suspect its same problem as described here:

http://stackoverflow.com/questions/20616351/exception-abstractmethoderror-javax-ws-rs-core-response-getstatusinfoljavax

**Comment by theprivateland** [comment]
What happened I had to exclude it manually in build and add jsr311 package with older jaxrs.

Can you at least update package dependencies in maven?

**Comment by thboileau** [comment]
Hi @theprivateland , I take care of it.

**Comment by theprivateland** [comment]
Thanks, temporarily I have resolved it by enforcing older JAXRS api in my gradle setup, but it may be worth updating implementation to full newer JAXRS (thou that would require more work than switching dependency).

**Comment by kaustubh-kasar** [comment]
Is this issue resolve?
If resolve then kindly share the **link** for downloading jar.

Thank you,
Kaustubh

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
