### ISSUE TITLE
NumberFormatException reading expires cookie in ClientResource.get()

### ISSUE THREAD

**Issue by cgatesman** [restlet/restlet-framework-java#1251]
Using Restlet 2.3.7.

It looks like this could be a bug with the URL's constructed Max-Age being in milliseconds instead of seconds, but I don't think Restlet should completely choke on a Max-Age larger than `Integer.MAX_VALUE`.

```
2016-12-12 22:53:14:289 WARNING: Error during cookie setting parsing. Header: ut_anon=cad673fa-ab90-43c1-854b-569d51a3f96b; expires=Sun, 14-Apr-3016 22:47:59 GMT; Max-Age=31536000000; path=/ org.restlet.engine.header.HeaderUtils copyResponseTransportHeaders
java.lang.NumberFormatException: For input string: "31536000000"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
  at java.lang.Integer.parseInt(Integer.java:583)
  at java.lang.Integer.valueOf(Integer.java:766)
  at org.restlet.engine.header.CookieSettingReader.readValue(CookieSettingReader.java:234)
  at org.restlet.engine.header.HeaderUtils.copyResponseTransportHeaders(HeaderUtils.java:760)
  at org.restlet.engine.adapter.ClientAdapter.readResponseHeaders(ClientAdapter.java:129)
  at org.restlet.engine.adapter.ClientAdapter.updateResponse(ClientAdapter.java:191)
  at org.restlet.engine.adapter.ClientAdapter.commit(ClientAdapter.java:105)
  at org.restlet.engine.adapter.HttpClientHelper.handle(HttpClientHelper.java:119)
  at org.restlet.Client.handle(Client.java:153)
  at org.restlet.routing.Filter.doHandle(Filter.java:150)
  at org.restlet.routing.Filter.handle(Filter.java:197)
  at org.restlet.resource.ClientResource.handle(ClientResource.java:1092)
  at org.restlet.resource.ClientResource.handleOutbound(ClientResource.java:1176)
  at org.restlet.resource.ClientResource.handle(ClientResource.java:1047)
  at org.restlet.resource.ClientResource.handle(ClientResource.java:1023)
  at org.restlet.resource.ClientResource.handle(ClientResource.java:928)
  at org.restlet.resource.ClientResource.get(ClientResource.java:638)
    .
    .
    .
```

**Comment by thboileau** [comment]
Thanks @cgatesman for reporting this.
I've fixed it by adding a log trace and using the Integer.MAX_VALUE.
Does it fit your needs?

**Comment by cgatesman** [comment]
That should be good.  Like I said, it's really a problem with the website, but it could be handled better by Restlet.  👍
