### ISSUE TITLE
Impossible to call a JAX-RS POST method with an entity not providing its mediatype

### ISSUE THREAD

**Issue by tmortagne** [restlet/restlet-framework-java#1271]
My used case is a REST client sending me a POST request with an entity without any media type set. It used to work fine in Restlet 2.0.14 but in 2.3.5 I'm getting the following error:

```
java.lang.NullPointerException
	at org.restlet.ext.jaxrs.internal.provider.ConverterProvider.isReadable(ConverterProvider.java:105)
	at org.restlet.ext.jaxrs.internal.wrappers.provider.SingletonProvider.isReadable(SingletonProvider.java:315)
	at org.restlet.ext.jaxrs.internal.wrappers.provider.JaxRsProviders.getBestReader(JaxRsProviders.java:322)
	at org.restlet.ext.jaxrs.internal.wrappers.params.EntityGetter.getValue(EntityGetter.java:93)
	at org.restlet.ext.jaxrs.internal.wrappers.params.ParameterList.get(ParameterList.java:1123)
	at org.restlet.ext.jaxrs.internal.wrappers.AbstractMethodWrapper.internalInvoke(AbstractMethodWrapper.java:160)
	at org.restlet.ext.jaxrs.internal.wrappers.ResourceMethod.invoke(ResourceMethod.java:283)
	at org.restlet.ext.jaxrs.JaxRsRestlet.invokeMethod(JaxRsRestlet.java:997)
	at org.restlet.ext.jaxrs.JaxRsRestlet.handle(JaxRsRestlet.java:746)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.engine.application.StatusFilter.doHandle(StatusFilter.java:140)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.engine.application.ApplicationHelper.handle(ApplicationHelper.java:75)
	at org.restlet.Application.handle(Application.java:385)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.routing.Router.doHandle(Router.java:422)
	at org.restlet.routing.Router.handle(Router.java:639)
	at org.restlet.routing.Filter.doHandle(Filter.java:150)
	at org.restlet.routing.Filter.handle(Filter.java:197)
	at org.restlet.engine.CompositeHelper.handle(CompositeHelper.java:202)
	at org.restlet.Component.handle(Component.java:408)
	at org.restlet.Server.handle(Server.java:507)
	at org.restlet.engine.connector.ServerHelper.handle(ServerHelper.java:63)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:143)
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1117)
        ...
```

Here is the method declaration in my resource:

```java
    /**
     * Import a XAR into a given wiki.
     *
     * @param wikiName the wiki name.
     * @param backup whether this is a backup pack.
     * @param history how to manage page version when importing pages.
     * @param is the input stream containing XAR data (POSTed by the client)
     * @return the information about the wiki.
     * @throws XWikiRestException if there was an error during import.
     */
    @POST Wiki importXAR(
            @PathParam("wikiName") String wikiName,
            @QueryParam("backup") @DefaultValue("false") Boolean backup,
            @QueryParam("history") @DefaultValue("add") String history,
            InputStream is
    ) throws XWikiRestException
```

**Comment by thboileau** [comment]
thanks @tmortagne for pointing this issue.
Thanks also for the pull request, I've tried to put a wider eye and found other places to check such NPE. So I just closed it.
It will be part of a 2.3.11.
