### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "org.restlet.engine.header.Header" issue with Andoird extension

### ISSUE THREAD

**Issue by thboileau** [restlet/restlet-framework-java#1294]
When upgrading my gradle script to restle versjon 2.3.12 and traget sdkversion 25 i keep getting noclassfound on org/restlet/engine/header/Header in runtime.
I'never get this on a lower version and targetsdk 23

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
      at android.os.AsyncTask$3.done(AsyncTask.java:330)
      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:776)
   Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/restlet/engine/header/Header;
      at org.restlet.ext.net.internal.HttpUrlConnectionCall.sendRequest(HttpUrlConnectionCall.java:350)
      at org.restlet.engine.adapter.ClientAdapter.commit(ClientAdapter.java:105)
      at org.restlet.engine.adapter.HttpClientHelper.handle(HttpClientHelper.java:119)
      at org.restlet.Client.handle(Client.java:153)
      at org.restlet.routing.Filter.doHandle(Filter.java:150)
      at org.restlet.routing.Filter.handle(Filter.java:197)
      at org.restlet.resource.ClientResource.handle(ClientResource.java:1093)
      at org.restlet.resource.ClientResource.handleOutbound(ClientResource.java:1179)
      at org.restlet.resource.ClientResource.handle(ClientResource.java:1048)
      at org.restlet.resource.ClientResource.handle(ClientResource.java:1024)
      at org.restlet.resource.ClientResource.handle(ClientResource.java:929)
      at org.restlet.resource.ClientResource.get(ClientResource.java:639)
      ......
      Caused by: java.lang.ClassNotFoundException: Didn't find class "org.restlet.engine.header.Header" on path: DexPathList....```

**Comment by thboileau** [comment]
next mail from Jon:

```
When removing some unessesary dependencies ending up with below, made things work: 

    compile "org.restlet.android:org.restlet.ext.jackson:${restletVersion}@jar"
    compile "org.restlet.android:org.restlet.ext.json:${restletVersion}@jar"
    compile "org.restlet.android:org.restlet:${restletVersion}@jar"


previous dependencies was: 
    compile "org.restlet.android:org.restlet:${restletVersion}@jar"
    compile "org.restlet.android:org.restlet.ext.xml:${restletVersion}@jar"
    compile "org.restlet.android:org.restlet.ext.jackson:${restletVersion}@jar"
    compile "org.restlet.android:org.restlet.ext.json:${restletVersion}@jar"
    compile "org.restlet.android:org.restlet.ext.httpclient:${restletVersion}@jar"
    compile "org.restlet.android:org.restlet.ext.net:2.1.7@jar"

```

**Comment by thboileau** [comment]
the issue was caused by this dependency: "org.restlet.android:org.restlet.ext.net:2.1.7".

In 2.1 version, the "Header" was supposed to be located in package: org.restlet.engine.header
Then in version 2.3, I think, such class has been moved to package:  org.restlet.data

And I suppose that this variable "${restletVersion}" is valuated to 2.3.x which leads to collision.
