### ISSUE TITLE
Silence/lower log level for "IOException: Connection reset by peer"

### ISSUE THREAD

**Issue by d4nirod** [restlet/restlet-framework-java#1309]
[Stack trace below]

Hi, I've been trying to get rid of these errors that are polluting our log, in my opinion they should still be logged but at `WARN` level as the connection is reset (dropped/closed weirdly?) by the client while the server is writing the response and there's isn't much we can do about it on our side. 

This is on Restlet 2.2.3, Tomcat 8.0.33, Java 8, Log4J 2.10 (+ org.restlet.ext.slf4j)  

`ServerAdapter.commit(ServerAdapter.java:197)` catches the  `ClientAbortException` and then through `org.restlet.engine.adapter.ServerCall.isBroken()` decides is **not "broken"** so it logs it as `java.util.logging.Level.SEVERE` which seems to map to `ERROR` in log4j.

Is there anyway I can get around this?

---
```
180112 16:27:02,932 ERROR [Server] An exception occured writing the response entity
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Connection reset by peer
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:393) ~[catalina.jar:8.0.33]
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:426) ~[tomcat-util.jar:8.0.33]
	at org.apache.tomcat.util.buf.ByteChunk.append(ByteChunk.java:283) ~[tomcat-util.jar:8.0.33]
	at org.apache.catalina.connector.OutputBuffer.writeByte(OutputBuffer.java:437) ~[catalina.jar:8.0.33]
	at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:81) ~[catalina.jar:8.0.33]
	at java.io.FilterOutputStream.write(FilterOutputStream.java:77) ~[?:1.8.0_152]
	at java.io.FilterOutputStream.write(FilterOutputStream.java:125) ~[?:1.8.0_152]
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221) ~[?:1.8.0_152]
	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291) ~[?:1.8.0_152]
	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295) ~[?:1.8.0_152]
	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141) ~[?:1.8.0_152]
	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229) ~[?:1.8.0_152]
	at org.restlet.representation.CharacterRepresentation.write(CharacterRepresentation.java:77) ~[org.restlet-2.2.3.jar:?]
	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:519) ~[org.restlet-2.2.3.jar:?]
	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:463) ~[org.restlet-2.2.3.jar:?]
	at org.restlet.ext.servlet.internal.ServletCall.sendResponse(ServletCall.java:430) ~[org.restlet.ext.servlet-2.2.3.jar:?]
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:196) [org.restlet-2.2.3.jar:?]
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:153) [org.restlet-2.2.3.jar:?]
	at org.restlet.ext.servlet.ServerServlet.service(ServerServlet.java:1118) [org.restlet.ext.servlet-2.2.3.jar:?]
	at com.farmerswife.cloudwife.server.api.rest.RestApiServlet.service(RestApiServlet.java:48) [classes/:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:?]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.33]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.33]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.33]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.33]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [catalina.jar:8.0.33]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.33]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [catalina.jar:8.0.33]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) [tomcat-coyote.jar:8.0.33]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-coyote.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502) [tomcat-coyote.jar:8.0.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458) [tomcat-coyote.jar:8.0.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
Caused by: java.io.IOException: Connection reset by peer
	... 46 more
```

**Comment by thboileau** [comment]
hello @d4nirod , unfortunately, the method `Call.isBroken` is static that does not help to override the current behaviour.
I see two things to do:
 - add the errors "Connection reset by peer" to the checks
 - help users to override the behaviour of `Call.isBroken`

What do you think @jlouvel ?

**Comment by jlouvel** [comment]
@thboileau After having a quick look at the code, I think we could:

- improve the implementation of Call.isBroken so that it properly detects the broken connection in case of Tomcat 8.0.33
- remove the "static" modifier if possible so that overriding it is possible

**Comment by thboileau** [comment]
thanks @jlouvel

**Comment by d4nirod** [comment]
@thboileau Wasn't this fixed in https://github.com/restlet/restlet-framework-java/commit/16e5d003c029b0d23da4a3fabcedaa973dc249c0 ? I think that went into 2.3.3
We've just upgraded from 2.2.x to 2.3.12, should be in production next week, and I was hoping the annoying messages would go away.

**Comment by thboileau** [comment]
@d4nirod 
oooh yep. I need to dive a little bit deeper.

**Comment by thboileau** [comment]
Hi @d4nirod 
I've tested using Restlet 2.3.12, Tomcat 8.5.27, Java 8 (don't use slf4j and log4j) and the log does not appear. The exception is correctly detected as "broken".
so now, let's try using log4j too.
