### ISSUE TITLE
Restlet application not terminating properly

### ISSUE THREAD

**Issue by PrimosK** [restlet/restlet-framework-java#1311]
Dear Restlet community,

we are using _Restlet_ and _Jetty server connector_ version _2.3.12_.

Let me explain the issue on the following SSCCE (imports skipped for brevity):

```
public class UsedPortServerTest extends ServerResource {

	private static final int PORT = 9999;

	public static void main(String[] args) throws Exception {

		final Server server = new Server(Protocol.HTTP, PORT, UsedPortServerTest.class);

		try {
			server.start();
		} catch (BindException bindException) {
			System.err.println("Port already in use...");
		}

		server.stop();
	}

	@Get
	public String toString() {
		return "Hello!";
	}

}
```

When running this application on the free 9999 port, the application will be started and then instantly ended as it should. This is the console output:
```
Starting the Jetty [HTTP/1.1] server on port 9999
Stopping the Jetty [HTTP/1.1] server on port 9999
```

Now if one tries to run the same example on the already used 9999 port, the `BindException` will be thrown as expected, but the application will then run indefinitely. It looks like Jetty leftover threads are preventing the application to end properly. This is the console output:
```
Starting the Jetty [HTTP/1.1] server on port 9999
Port already in use...
13:10:30.814 [main] WARN  FAILED ServerConnector@4de5031f{HTTP/1.1}{0.0.0.0:9999}: java.net.BindException: Address already in use: bind
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.restlet.ext.jetty.JettyServerHelper.start(JettyServerHelper.java:794)
	at org.restlet.Server.start(Server.java:579)
	at UsedPortServerTest.main(UsedPortServerTest.java:18)
13:10:30.816 [main] WARN  FAILED org.restlet.ext.jetty.JettyServerHelper$WrappedServer@105fece7: java.net.BindException: Address already in use: bind
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.restlet.ext.jetty.JettyServerHelper.start(JettyServerHelper.java:794)
	at org.restlet.Server.start(Server.java:579)
	at UsedPortServerTest.main(UsedPortServerTest.java:18)
```

The expected behaviour in this case would be for the application to stop as the server is not properly started in the first place.

Thread dump report:
[UsedPortServerTest_threads_report.txt](https://github.com/restlet/restlet-framework-java/files/1638864/UsedPortServerTest_threads_report.txt)

**Comment by thboileau** [comment]
thanks @PrimosK for pointing this issue!
Some resources were not released when the Jetty server fails to start.
The fix will be part of 2.3.13.
