### ISSUE TITLE
restlet 2.2.1 JAX-RS and spring Integration，Request parameter string missing

### ISSUE THREAD

**Issue by dngzs** [restlet/restlet-framework-java#1338]
hello,I used spring to inherit the restlet and Jax-rs,But found that there seems to be thread safety issues，The parameters are always confusing，I don't know if it is my configuration problem.help me,I am vexed，thx,Configuration is as follows：

jdk1.7

<bean id="component" class="org.restlet.ext.spring.SpringComponent">
        <property name="defaultTarget" ref="restServer"/>
 </bean>

<bean id="component" class="org.restlet.ext.spring.SpringComponent">
        <property name="defaultTarget" ref="restServer"/>
    </bean>

    <bean id="restServer" class="org.restlet.ext.jaxrs.JaxRsApplication">
        <property name="objectFactory" ref="v5SpringJaxObjectFactory"/>
        <property name="applications" ref="v5SpringJaxApplication"/>
    </bean>

    <bean id="v5SpringJaxObjectFactory" class="com.demo.restlet.V5SpringJaxObjectFactory">
        <constructor-arg ref="v5JaxBeanCollection"/>
    </bean>

    <bean id="v5SpringJaxApplication" class="com.demo.restlet.V5SpringJaxApplication">
        <constructor-arg ref="v5JaxBeanCollection"/>
    </bean>

    <bean id="v5JaxBeanCollection" class="com.demo.restlet.V5JaxBeanCollection"/>

  public class V5SpringJaxObjectFactory implements ObjectFactory {
   
     private V5JaxBeanCollection myBeanCollection;
     public V5SpringJaxObjectFactory(final V5JaxBeanCollection beanCollection) {
         this.myBeanCollection = beanCollection;
     }
   
    @Override
     public <T> T getInstance(final Class<T> jaxRsClass) throws InstantiateException {
         T bean = myBeanCollection.getBean(jaxRsClass);
         return bean;
    }
}

  public class V5SpringJaxApplication extends javax.ws.rs.core.Application {
    
    private V5JaxBeanCollection myBeanCollection;

    public V5SpringJaxApplication(final V5JaxBeanCollection beanCollection) {
        this.myBeanCollection = beanCollection;
    }
    @Override
    public Set<Class<?>> getClasses() {
        return myBeanCollection.getBeanTypes();
    }
}

public class V5JaxBeanCollection implements BeanFactoryAware, InitializingBean {

    private static final Logger logger = LoggerFactory.getLogger(V5JaxBeanCollection.class);

    private static final Class<?> V5_BASE_RESOURCE_CLASS=V5Resource.class;

    private Set<Class<?>> beanTypes = new HashSet<Class<?>>();

    private Set<String> beanNames = new HashSet<String>();

    private ListableBeanFactory beanFactory;

    @Override
    public void setBeanFactory(BeanFactory beanFactory) throws BeansException {
        this.beanFactory = (ListableBeanFactory) beanFactory;
    }

    public Set<Class<?>> getBeanTypes() {
        return beanTypes;
    }
    
    @Override
    public void afterPropertiesSet() throws Exception {
        String[] resourceClassNameList=beanFactory.getBeanNamesForType(V5_BASE_RESOURCE_CLASS);
        if(resourceClassNameList!=null && resourceClassNameList.length>0){
            for(String className:resourceClassNameList){
                beanTypes.add(beanFactory.getType(className));
            }
        }
    }

    public <T> T getBean(Class<T> clazz){
        return this.beanFactory.getBean(clazz);
    }

}

@Service
@Path("/v2")
public class Test2Resource extends ServerResource implements V5Resource{
    private static final Logger logger = LoggerFactory.getLogger(Test2Resource.class);

    @POST
    @Path("test2")
    public String test1(@Encoded @FormParam("seq") String json) throws Exception{
        logger.info(json);
        Data data = JSONObject.parseObject(json, Data.class);
        return "success";
    }
}

@Service
@Path("/v1")
public class Test1Resource extends ServerResource implements V5Resource {

    private static final Logger logger = LoggerFactory.getLogger(Test1Resource.class);

    @POST
    @Path("test1")
    public String test1(@Encoded @FormParam("seq") String json) throws Exception{
        logger.info(json);
        Data data = JSONObject.parseObject(json, Data.class);
        if("error".equals(data.getName())){
            logger.error("error--");
            throw new RuntimeException("error--");
        }
        return "success";
    }

}

web.xml Configuration and test case
![test1](https://user-images.githubusercontent.com/18388958/51595407-9c70af80-1f31-11e9-9472-fdb475f3ba57.png)
![test2](https://user-images.githubusercontent.com/18388958/51595409-9d094600-1f31-11e9-87e5-5bc489e18d7f.png)
![web xml1](https://user-images.githubusercontent.com/18388958/51595411-9da1dc80-1f31-11e9-8fec-13917500e7be.png)
![web xml2](https://user-images.githubusercontent.com/18388958/51595414-9da1dc80-1f31-11e9-8dbc-41cc8295a9c8.png)

Error message

2019-01-23 17:20:17,262 ERROR[com.demo.restlet.Test1Resource:26]- error--
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.restlet.ext.jaxrs.internal.wrappers.AbstractMethodWrapper.internalInvoke(AbstractMethodWrapper.java:171)
	at org.restlet.ext.jaxrs.internal.wrappers.ResourceMethod.invoke(ResourceMethod.java:292)
	at org.restlet.ext.jaxrs.JaxRsRestlet.invokeMethod(JaxRsRestlet.java:1005)
	at org.restlet.ext.jaxrs.JaxRsRestlet.handle(JaxRsRestlet.java:754)

help me，The source code of the project is here
https://pan.baidu.com/s/1Q4pwax2kYbEK_g2uETKliA   ， I hope to hear from you.I am sorry for your work.

**Comment by dngzs** [comment]
> hello,I used spring to inherit the restlet and Jax-rs,But found that there seems to be thread safety issues，The parameters are always confusing，I don't know if it is my configuration problem.help me,I am vexed，thx,Configuration is as follows：
> 
> ```
> <bean id="restServer" class="org.restlet.ext.jaxrs.JaxRsApplication">
>     <property name="objectFactory" ref="v5SpringJaxObjectFactory"/>
>     <property name="applications" ref="v5SpringJaxApplication"/>
> </bean>
> 
> <bean id="v5SpringJaxObjectFactory" class="com.demo.restlet.V5SpringJaxObjectFactory">
>     <constructor-arg ref="v5JaxBeanCollection"/>
> </bean>
> 
> <bean id="v5SpringJaxApplication" class="com.demo.restlet.V5SpringJaxApplication">
>     <constructor-arg ref="v5JaxBeanCollection"/>
> </bean>
> 
> <bean id="v5JaxBeanCollection" class="com.demo.restlet.V5JaxBeanCollection"/>
> ```
> public class V5SpringJaxObjectFactory implements ObjectFactory {
> 
> ```
>  private V5JaxBeanCollection myBeanCollection;
>  public V5SpringJaxObjectFactory(final V5JaxBeanCollection beanCollection) {
>      this.myBeanCollection = beanCollection;
>  }
> 
> @Override
>  public <T> T getInstance(final Class<T> jaxRsClass) throws InstantiateException {
>      T bean = myBeanCollection.getBean(jaxRsClass);
>      return bean;
> }
> ```
> }
> 
> public class V5SpringJaxApplication extends javax.ws.rs.core.Application {
> 
> ```
> private V5JaxBeanCollection myBeanCollection;
> 
> public V5SpringJaxApplication(final V5JaxBeanCollection beanCollection) {
>     this.myBeanCollection = beanCollection;
> }
> @Override
> public Set<Class<?>> getClasses() {
>     return myBeanCollection.getBeanTypes();
> }
> ```
> }
> 
> public class V5JaxBeanCollection implements BeanFactoryAware, InitializingBean {
> 
> ```
> private static final Logger logger = LoggerFactory.getLogger(V5JaxBeanCollection.class);
> 
> private static final Class<?> V5_BASE_RESOURCE_CLASS=V5Resource.class;
> 
> private Set<Class<?>> beanTypes = new HashSet<Class<?>>();
> 
> private Set<String> beanNames = new HashSet<String>();
> 
> private ListableBeanFactory beanFactory;
> 
> @Override
> public void setBeanFactory(BeanFactory beanFactory) throws BeansException {
>     this.beanFactory = (ListableBeanFactory) beanFactory;
> }
> 
> public Set<Class<?>> getBeanTypes() {
>     return beanTypes;
> }
> 
> @Override
> public void afterPropertiesSet() throws Exception {
>     String[] resourceClassNameList=beanFactory.getBeanNamesForType(V5_BASE_RESOURCE_CLASS);
>     if(resourceClassNameList!=null && resourceClassNameList.length>0){
>         for(String className:resourceClassNameList){
>             beanTypes.add(beanFactory.getType(className));
>         }
>     }
> }
> 
> public <T> T getBean(Class<T> clazz){
>     return this.beanFactory.getBean(clazz);
> }
> ```
> }
> 
> @service
> @path("/v2")
> public class Test2Resource extends ServerResource implements V5Resource{
> private static final Logger logger = LoggerFactory.getLogger(Test2Resource.class);
> 
> ```
> @POST
> @Path("test2")
> public String test1(@Encoded @FormParam("seq") String json) throws Exception{
>     logger.info(json);
>     Data data = JSONObject.parseObject(json, Data.class);
>     return "success";
> }
> ```
> }
> 
> @service
> @path("/v1")
> public class Test1Resource extends ServerResource implements V5Resource {
> 
> ```
> private static final Logger logger = LoggerFactory.getLogger(Test1Resource.class);
> 
> @POST
> @Path("test1")
> public String test1(@Encoded @FormParam("seq") String json) throws Exception{
>     logger.info(json);
>     Data data = JSONObject.parseObject(json, Data.class);
>     if("error".equals(data.getName())){
>         logger.error("error");
>         throw new RuntimeException("error");
>     }
>     return "success";
> }
> ```
> }
> 
> org.springframework.web.context.ContextLoaderListener org.restlet.component component contextConfigLocation classpath*:spring.xml ltlv5RestServlet org.restlet.ext.spring.SpringServerServlet 1 ltlv5RestServlet /rest/*
> help me，The source code of the project is here
> https://pan.baidu.com/s/1Q4pwax2kYbEK_g2uETKliA ， thx

**Comment by dngzs** [comment]
reopen
