### ISSUE TITLE
UriInfo.getQueryParameters().containsKey is broken for UnmodifiableMultivaluedMap with case insesitive search

### ISSUE THREAD

**Issue by MarkKharitonov** [restlet/restlet-framework-java#640]
A return statement is missing in the `UnmodifiableMultivaluedMap.containsKey` implementation.

**Comment by abstratt** [comment]
FYI, encountered this too in 2.2.0: 

```
java.lang.NullPointerException
	at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1026)
	at java.util.Collections$UnmodifiableList.<init>(Collections.java:1302)
	at java.util.Collections.unmodifiableList(Collections.java:1287)
	at org.restlet.ext.jaxrs.internal.core.UnmodifiableMultivaluedMap.get(UnmodifiableMultivaluedMap.java:193)
	at org.restlet.ext.jaxrs.internal.core.UnmodifiableMultivaluedMap.get(UnmodifiableMultivaluedMap.java:55)
	at java.util.Map.getOrDefault(Map.java:588)
```

**Comment by abstratt** [comment]
A workaround is to stick to entrySet() to access query parameters.
