### ISSUE TITLE
Redirector (serverRedirect) fails to redirect a Decoderepresentation and Content-Length is not adjusted.

### ISSUE THREAD

**Issue by caleryn** [restlet/restlet-framework-java#773]
the `Content Length` being supplied by the current redirector code comes straight from the source headers and is not adjusted through the `DecodeRepresentation`.
This results in a monitor being closed prematurely and the following Exception is thrown.

```
org.simpleframework.http.core.ProducerException: Error sending response
	at org.simpleframework.http.core.FixedProducer.produce(FixedProducer.java:158)
	at org.simpleframework.http.core.Transfer.write(Transfer.java:196)
	at org.simpleframework.http.core.Transfer.write(Transfer.java:178)
	at org.simpleframework.http.core.ResponseBuffer.write(ResponseBuffer.java:208)
	at org.simpleframework.http.core.ResponseBuffer.write(ResponseBuffer.java:179)
	at org.simpleframework.http.core.ResponseBuffer.write(ResponseBuffer.java:158)
	at org.restlet.engine.io.BioUtils.copy(BioUtils.java:82)
	at org.restlet.engine.application.DecodeRepresentation.write(DecodeRepresentation.java:248)
	at org.restlet.engine.adapter.ServerCall.writeResponseBody(ServerCall.java:519)
	at org.restlet.engine.adapter.ServerCall.sendResponse(ServerCall.java:463)
	at org.restlet.engine.adapter.ServerAdapter.commit(ServerAdapter.java:196)
	at org.restlet.engine.adapter.HttpServerHelper.handle(HttpServerHelper.java:153)
	at org.restlet.ext.simple.internal.SimpleContainer.handle(SimpleContainer.java:80)
	at org.simpleframework.http.core.Dispatcher.dispatch(Dispatcher.java:121)
	at org.simpleframework.http.core.Dispatcher.run(Dispatcher.java:103)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: org.simpleframework.http.core.ProducerException: Response content complete
	at org.simpleframework.http.core.FixedProducer.produce(FixedProducer.java:147)
	... 17 more
```
I am able to work around this issue, by extending the redirector class and overriding serverRedirect as follows;
```java
    @Override
    protected void serverRedirect(Restlet next, Reference targetRef,
            Request request, Response response) {
        if (next == null) {
            getLogger().warning(
                    "No next Restlet provided for server redirection to "
                    + targetRef);
        } else {
            // Save the base URI if it exists as we might need it for
            // redirections
            Reference resourceRef = request.getResourceRef();
            Reference baseRef = resourceRef.getBaseRef();

            // Reset the protocol and let the dispatcher handle the protocol
            request.setProtocol(null);

            // Update the request to cleanly go to the target URI
            request.setResourceRef(targetRef);
            request.getAttributes().remove(HeaderConstants.ATTRIBUTE_HEADERS);
            next.handle(request, response);

            Representation representation = response.getEntity();
            if (representation instanceof DecodeRepresentation) {
                representation = new EncodeRepresentation(Encoding.GZIP, representation);
            }

            // Allow for response rewriting and clean the headers
            response.setEntity(rewrite(representation));
            response.getAttributes().remove(HeaderConstants.ATTRIBUTE_HEADERS);
            request.setResourceRef(resourceRef);

            // In case of redirection, we may have to rewrite the redirect URI
            if (response.getLocationRef() != null) {
                Template rt = new Template(this.targetTemplate);
                rt.setLogger(getLogger());
                int matched = rt.parse(response.getLocationRef().toString(),
                        request);

                if (matched > 0) {
                    String remainingPart = (String) request.getAttributes()
                            .get("rr");

                    if (remainingPart != null) {
                        response.setLocationRef(baseRef.toString()
                                + remainingPart);
                    }
                }
            }
        }
    }
```
where my source provides GZIP encoded data. However I do not believe that this is a good solution as it would almost certainly be better not to decode the representation at all but rather pass on the original untouched, where a client can handle the encoding.  I am not sure how to suggest best to proceed with that change to BioUtils or the DecodeRepresentation, or ?

This bug affects versions 2.1.2 and 2.2m3 however 2.0.15 works.

Regards

**Comment by thboileau** [comment]
Hi @caleryn ,

I've made some tests, tring to reproduce your issue, using RF 2.3.2, but vainly.
My test case is composed of 2 applications (RedirectorApplication, and RedirectedApplication). The former redirects any call to the latter, and in addition, decodes any encoded representations. The latter encodes any representations, using the Encoder.

 - RedirectedApplication
```java
public class RedirectedApplication extends Application {

    @Override
    public Restlet createInboundRoot() {
        Router router = new Router();

        router.attach("/hello", new Restlet(getContext()) {
            @Override
            public void handle(Request request, Response response) {
                response.setEntity("hello, world", MediaType.TEXT_PLAIN);
            }
        });

        Encoder encoder = new Encoder(getContext(), false, true,
                getEncoderService());
        getEncoderService().setMinimumSize(EncoderService.ANY_SIZE);
        encoder.setNext(router);
        return encoder;
    }

}
```
 - RedirectorApplication
```java
public class RedirectorApplication extends Application {

    private int port;

    public RedirectorApplication(int port) {
        this.port = port;
    }

    @Override
    public Restlet createInboundRoot() {
        Redirector r = new Redirector(getContext(), "http://localhost:" + port
                + "/target{rr}");
        return r;
    }

    @Override
    public Restlet createOutboundRoot() {
        // Wrap any encoded entity withh a DecodeRepresentation
        Decoder decoder = new Decoder(getContext(), true, true);
        decoder.setNext(super.createOutboundRoot());
        return decoder;
    }
}
```
 - main class:
```java
public class RedirectTest {

    public static void main(String[] args) throws Exception {
        int port = 9192;
        Component c = new Component();
        c.getServers().add(Protocol.HTTP, port);
        c.getClients().add(Protocol.HTTP);
        
        c.getDefaultHost().attach(new RedirectorApplication(port));
        c.getDefaultHost().attach("/target", new RedirectedApplication());

        c.start();
    }
}
```

**Comment by caleryn** [comment]
@thboileau I will have a look to see if the issue still exists in 2.3.x for me, it is possible that it was an issue with the connectors used at the time, or that other changes made since have also fixed this.

**Comment by thboileau** [comment]
Hi @caleryn : had you a chance to see if the issue still occurs?

**Comment by caleryn** [comment]
I have been unable to recreate the origional issue, sorry about the delay.
