### ISSUE TITLE
Fix test suite

### ISSUE THREAD

**Issue by jlouvel** [restlet/restlet-framework-java#881]
Looking at the Travis build the test suite fails in JSE edition.

My local Ant test suite logs show this issue due to the JAX-RS 2.0 library upgrade (related to RESTEasy):

Testcase: testIae took 0.054 sec
    Caused an ERROR
javax/ws/rs/core/Configurable
java.lang.NoClassDefFoundError: javax/ws/rs/core/Configurable
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$100(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:60)
    at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:117)
    at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:105)
    at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:91)
    at javax.ws.rs.core.Response$ResponseBuilder.newInstance(Response.java:356)
    at javax.ws.rs.core.Response.status(Response.java:127)
    at org.restlet.test.ext.jaxrs.services.providers.IllegalArgExcMapper.toResponse(IllegalArgExcMapper.java:72)
    at org.restlet.test.ext.jaxrs.services.providers.IllegalArgExcMapper.toResponse(IllegalArgExcMapper.java:56)
    at org.restlet.ext.jaxrs.internal.wrappers.provider.JaxRsProviders.convert(JaxRsProviders.java:292)
    at org.restlet.test.ext.jaxrs.ExceptionMappersTest.convert(ExceptionMappersTest.java:112)
    at org.restlet.test.ext.jaxrs.ExceptionMappersTest.testIae(ExceptionMappersTest.java:135)
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.Configurable
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
# workload: 2d (complete all unimplemented methods)

**Comment by jlouvel** [comment]
If time permit, let's consider it for 2.3.1

**Comment by jlouvel** [comment]
Closing as we are removing JAX-RS in branch 2.5
