### ISSUE TITLE
StackOverflowError with simple app and JavaEE/Jetty

### ISSUE THREAD

**Issue by jlouvel** [restlet/restlet-framework-java#921]
Encountered by Tony Tam: I’ve followed two tutorials but keep getting this.
http://numberformat.wordpress.com/2011/02/20/restlet-hello-world/

(updated the restlet to 2.2.1)

HTTP ERROR 500

Problem accessing /app/hello. Reason:

```
Server Error
```

Caused by:

java.lang.StackOverflowError
    at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
    at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
    at java.io.File.isDirectory(File.java:843)
    at org.eclipse.jetty.util.resource.FileResource.<init>(FileResource.java:107)
    at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:103)
    at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:83)
    at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:198)
    at org.eclipse.jetty.util.resource.Resource.newResource(Resource.java:134)
    at org.eclipse.jetty.util.resource.FileResource.addPath(FileResource.java:157)
    at org.eclipse.jetty.server.handler.ContextHandler.getResource(ContextHandler.java:1489)
    at org.eclipse.jetty.webapp.WebAppContext.getResource(WebAppContext.java:321)
    at org.mortbay.jetty.plugin.JettyWebAppContext.getResource(JettyWebAppContext.java:264)
    at org.eclipse.jetty.server.handler.ContextHandler.getResourcePaths(ContextHandler.java:1544)
    at org.mortbay.jetty.plugin.JettyWebAppContext.getResourcePaths(JettyWebAppContext.java:337)
    at org.eclipse.jetty.server.handler.ContextHandler$Context.getResourcePaths(ContextHandler.java:1832)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:114)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:122)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:122)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:122)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:122)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:122)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:122)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:122)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:122)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:122)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:122)
    at org.restlet.ext.servlet.internal.ServletWarEntity.<init>(ServletWarEntity.java:122)

**Comment by jlouvel** [comment]
In Restlet 3.0 we will be dropping support for Servlet to focus on deployment to cloud native architectures, microservices, service mesh, reducing the value of Servlet containers.
